# Generated by Django 5.0 on 2024-01-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=25, null=True)),
                ('course_type', models.CharField(blank=True, max_length=7)),
                ('credits', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weighted_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('current_unweighted_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
    ]
