# Generated by Django 5.0 on 2024-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
