# Generated by Django 5.0 on 2024-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalcapp', '0003_alter_course_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.CharField(blank=True, max_length=7, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
